"""CLI entry point for the ADCo checker.

Usage:
    uv run python -m checker <sandbox_dir> [--model MODEL] [--verbose]
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid

from dotenv import load_dotenv
from google.genai import types

from src.code_checker.agent import create_checker_agent
from src.code_checker.models import CheckerOutput
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

load_dotenv(os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

DEFAULT_MODEL = "gemini-3.5-flash-lite"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="ADCo Checker — safety audit for sandbox-optimized code",
    )
    parser.add_argument(
        "sandbox_dir",
        help="Path to the sandbox directory generated by the rewriter",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Gemini model to use (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--original",
        default="",
        help="Path to the original (pre-rewrite) codebase directory for diff comparison",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print detailed agent activity",
    )
    args = parser.parse_args()

    sandbox = os.path.abspath(args.sandbox_dir)
    if not os.path.isdir(sandbox):
        print(f"ERROR: not a directory: {sandbox}", file=sys.stderr)
        sys.exit(2)

    try:
        result = asyncio.run(
            _run_checker(sandbox, original=args.original, model=args.model, verbose=args.verbose)
        )
    except Exception as exc:
        print(f"\n=== Checker ===")
        print(f"Run:      fail")
        print(f"Error:    {exc}", file=sys.stderr)
        sys.exit(1)

    checker_output = result.get("checker_output", {})
    if isinstance(checker_output, dict):
        check_status = checker_output.get("status", "FAIL")
        issues = checker_output.get("issues", [])
        summary = checker_output.get("summary", "")
    elif isinstance(checker_output, CheckerOutput):
        check_status = checker_output.status
        issues = checker_output.issues
        summary = checker_output.summary
    else:
        check_status = "FAIL"
        issues = []
        summary = "Failed to parse checker output"

    print(f"\n=== Checker ===")
    print(f"Run:      success")
    print(f"Result:   {check_status}")
    print(f"Sandbox:  {sandbox}")
    print(f"Model:    {args.model}")
    print(f"Issues:   {len(issues)}")

    if summary:
        print(f"Summary:  {summary}")

    if issues:
        print("\nIssues found:")
        for i, issue in enumerate(issues, 1):
            if isinstance(issue, dict):
                print(
                    f"  {i}. [{issue.get('severity', '?')}] [{issue.get('category', '?')}] "
                    f"{issue.get('file', '?')}:{issue.get('line', 0)} — "
                    f"{issue.get('description', '')}"
                )
            else:
                print(
                    f"  {i}. [{issue.severity}] [{issue.category}] "
                    f"{issue.file}:{issue.line} — {issue.description}"
                )

    sys.exit(0)


async def _run_checker(
    sandbox: str, original: str = "", model: str = DEFAULT_MODEL, verbose: bool = False
) -> dict:
    session_service = InMemorySessionService()
    sid = uuid.uuid4().hex[:12]
    app_name = "adco_checker"

    state = {"sandbox": sandbox}
    if original and os.path.isdir(original):
        state["original"] = os.path.abspath(original)

    await session_service.create_session(
        app_name=app_name,
        user_id="checker",
        session_id=sid,
        state=state,
    )

    agent = create_checker_agent(model)
    runner = Runner(
        agent=agent, app_name=app_name, session_service=session_service
    )

    original_note = ""
    if original and os.path.isdir(original):
        original_note = (
            f"\nThe original (pre-rewrite) codebase is at: {original}\n"
            f"Use read_original_file() to compare against the optimized code "
            f"for every regression check."
        )

    user_message = (
        f"Audit the sandbox-optimized codebase at: {sandbox}\n"
        f"{original_note}\n"
        f"Find modified files, read them, and check for correctness, "
        f"safety, regression, completeness, and performance issues. "
        f"Report your findings as structured JSON."
    )

    async for event in runner.run_async(
        user_id="checker",
        session_id=sid,
        new_message=types.Content(
            role="user", parts=[types.Part(text=user_message)]
        ),
    ):
        if event.content and event.content.parts:
            for part in event.content.parts:
                if part.function_call and verbose:
                    print(
                        f"  [tool] {part.function_call.name}({part.function_call.args})"
                    )
                if part.function_response and verbose:
                    resp = str(part.function_response.response)
                    print(f"  [tool result] {resp[:160]}")
                if part.text and not event.partial and verbose:
                    print(part.text, end="")

    session = await session_service.get_session(
        app_name=app_name, user_id="checker", session_id=sid
    )
    state = dict(session.state)

    return state
