"""Root orchestrator agent for the intent analyzer module."""
import asyncio
from typing import Union

from google.adk.agents import LlmAgent
from google.adk.models import BaseLlm
from google.adk.tools.agent_tool import AgentTool

from src.intent_analyzer.sub_agents.file_selector.agent import create_file_selector_agent
from src.intent_analyzer.sub_agents.intent_extractor.agent import create_intent_extractor_agent
from src.intent_analyzer.tools.scanner import scan_codebase

INTENT_ANALYZER_PROMPT = """You are the ADCo Codebase Intent Analyzer Orchestrator. Your mission is to coordinate the 3-step codebase analysis pipeline using your tools.

<critical_instructions>
- You are a coordinator agent ONLY. You possess NO internal knowledge about the target codebase or benchmark.
- You MUST NOT write an analysis or summary yourself.
- You MUST execute all 3 tool calls in sequence.
- NEVER stop or output a final summary after `file_selector`. You MUST proceed to call `intent_extractor`.
- The pipeline requires structured output generated by `intent_extractor`. If you do not call `intent_extractor`, the pipeline will fail.
</critical_instructions>

## Pipeline Steps

<step_1>
**Action**: Call the `scan_codebase` tool.
**Description**: Scans the directory structure of the target codebase. The tool returns the file listing and stores it in session state.
</step_1>

<step_2>
**Action**: Call the `file_selector` sub-agent tool.
**Description**: Pass the file listing from step 1 under the heading "## Project listing". It will identify database-relevant files and store `file_selector_output` in session state.
</step_2>

<step_3>
**Action**: Call the `intent_extractor` sub-agent tool.
**Description**: Immediately call `intent_extractor` after step 2. Instruct it: "Read the selected files and extract database interaction intent, optimization targets, and workload profile."
</step_3>

## Execution Rules
- **Rule 1**: Call exactly ONE tool per turn, then wait for the tool output.
- **Rule 2**: Always execute step 1 -> step 2 -> step 3 in exact order.
- **Rule 3**: Do NOT output any natural language analysis until AFTER step 3 (`intent_extractor`) has executed.
"""


def make_buffer_callback(buffer_time: float = 0.0):
    if buffer_time <= 0:
        return None
    async def buffer_callback(callback_context=None, llm_request=None, **kwargs):
        await asyncio.sleep(buffer_time)
    return buffer_callback


def create_intent_analyzer_agent(model: Union[str, BaseLlm] = "gemini-3.5-flash-lite", buffer_time: float = 0.0) -> LlmAgent:
    """Create and return the root intent analyzer LlmAgent."""
    return LlmAgent(
        name="intent_analyzer",
        model=model,
        instruction=INTENT_ANALYZER_PROMPT,
        description="ADCo codebase intent analyzer — scans codebase, selects DB files, and extracts optimization targets and workload profile.",
        tools=[
            scan_codebase,
            AgentTool(create_file_selector_agent(model, buffer_time=buffer_time)),
            AgentTool(create_intent_extractor_agent(model, buffer_time=buffer_time)),
        ],
        before_model_callback=make_buffer_callback(buffer_time),
    )


def create_root_agent(model: Union[str, BaseLlm] = "gemini-3.5-flash-lite", buffer_time: float = 0.0) -> LlmAgent:
    """Alias for create_intent_analyzer_agent for consistency."""
    return create_intent_analyzer_agent(model, buffer_time=buffer_time)
