"""SQL to Python database application compiler."""

import argparse
import os
import re
import glob


def parse_query_num(filename: str) -> int:
    """Extract query number from filename like 'query12.sql' -> 12."""
    match = re.search(r"query(\d+)\.sql$", filename)
    if not match:
        raise ValueError(f"Invalid query filename: {filename}")
    return int(match.group(1))


def compile_queries(input_dir: str, output_dir: str) -> None:
    # Find all query*.sql files
    query_files = glob.glob(os.path.join(input_dir, "query*.sql"))
    if not query_files:
        print(f"No query*.sql files found in {input_dir}")
        return

    # Sort files numerically
    sorted_files = []
    for f in query_files:
        try:
            num = parse_query_num(f)
            sorted_files.append((num, f))
        except ValueError:
            continue
    sorted_files.sort()

    os.makedirs(output_dir, exist_ok=True)
    out_file = os.path.join(output_dir, "db_app.py")

    code_lines = [
        '"""',
        'Database application for stats queries.',
        'Auto-generated by pycompiler. Do not edit manually.',
        '"""',
        '',
        'import logging',
        'import os',
        'import sys',
        '',
        'import psycopg2',
        'from psycopg2.extras import RealDictCursor',
        '',
        'logging.basicConfig(',
        '    level=logging.INFO,',
        '    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",',
        ')',
        'logger = logging.getLogger(__name__)',
        '',
        '',
        'class DatabaseClient:',
        '    def __init__(self):',
        '        self._conn = None',
        '',
        '    def connect(self):',
        '        self._conn = psycopg2.connect(',
        '            host=os.environ.get("DB_HOST", "localhost"),',
        '            port=int(os.environ.get("DB_PORT", 5432)),',
        '            dbname=os.environ.get("DB_NAME", "stats"),',
        '            user=os.environ.get("DB_USER", "postgres"),',
        '            password=os.environ.get("DB_PASSWORD", ""),',
        '        )',
        '        logger.info("Connected to database")',
        '',
        '    def close(self):',
        '        if self._conn:',
        '            self._conn.close()',
        '            logger.info("Connection closed")',
        '',
        '    def __enter__(self):',
        '        self.connect()',
        '        return self',
        '',
        '    def __exit__(self, *_):',
        '        self.close()',
        ''
    ]

    for num, filepath in sorted_files:
        with open(filepath, "r", encoding="utf-8") as f:
            sql_content = f.read().strip()
        
        # Add the query constant with markers
        code_lines.append(f"    # --- query{num} ---")
        code_lines.append(f'    QUERY_{num} = """\\')
        code_lines.append(sql_content)
        code_lines.append('"""')
        code_lines.append(f"    # [END query{num}]")
        code_lines.append("")

        # Add the execution method
        code_lines.append(f"    def run_query{num}(self):")
        code_lines.append(f'        logger.info("Executing query{num}")')
        code_lines.append("        with self._conn.cursor(cursor_factory=RealDictCursor) as cur:")
        code_lines.append(f"            cur.execute(self.QUERY_{num})")
        code_lines.append("            results = cur.fetchall()")
        code_lines.append(f'            logger.info("query{num} returned %d row(s)", len(results))')
        code_lines.append("            return results")
        code_lines.append("")

    # Add main function
    code_lines.append("def main():")
    code_lines.append("    with DatabaseClient() as client:")
    code_lines.append("        try:")
    for num, _ in sorted_files:
        code_lines.append(f"            print(client.run_query{num}())")
    code_lines.append("        except Exception as exc:")
    code_lines.append('            logger.error("Query failed: %s", exc)')
    code_lines.append("            sys.exit(1)")
    code_lines.append("")
    code_lines.append("")
    code_lines.append('if __name__ == "__main__":')
    code_lines.append("    main()")

    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(code_lines) + "\n")
    print(f"Successfully compiled {len(sorted_files)} queries to {out_file}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile query*.sql files into a Python database app")
    parser.add_argument("--input-dir", required=True, help="Directory containing query*.sql files")
    parser.add_argument("--output-dir", required=True, help="Directory where db_app.py will be generated")
    args = parser.parse_args()

    compile_queries(args.input_dir, args.output_dir)


if __name__ == "__main__":
    main()
